# Generated by Django 4.0.6 on 2022-07-16 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea_applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas_id', to='idea.idea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
