# Generated by Django 4.0.6 on 2022-07-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0003_remove_idea_short_descirption_idea_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea_applicants',
            name='skills',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
