# Generated by Django 4.0.6 on 2022-07-19 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0004_idea_applicants_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea_applicants',
            name='skills',
        ),
    ]
