# Generated by Django 4.0.6 on 2022-07-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0005_remove_idea_applicants_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea_applicants',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='idea_applicants',
            name='skills',
            field=models.TextField(default=''),
        ),
    ]
