# Generated by Django 4.0.6 on 2022-07-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.TextField()),
                ('password', models.TextField()),
                ('name', models.TextField()),
                ('branch', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
