# Generated by Django 4.0.6 on 2022-07-19 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_useraccount_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='userId',
        ),
    ]
