# Generated by Django 4.0.6 on 2022-07-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_useraccount_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='id',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='Username',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
